global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: backend
    static_configs:
      - targets: ['backend:8000']
        labels:
          service: backend

  - job_name: backend-dvc
    static_configs:
      - targets: ['backend-dvc:8000']
        labels:
          service: backend-dvc
