// This file is auto-generated by @hey-api/openapi-ts

export type _ContentsItemBase = {
  name: string
  path: string
  type: string | null
  size: number | null
  in_repo: boolean
  content?: string | null
  url?: string | null
  calkit_object?: {
    [key: string]: unknown
  } | null
  lock?: ItemLock | null
  storage?: "git" | "dvc" | "dvc-zip" | null
  stage?: string | null
}

export type AccountPublic = {
  name: string
  github_name: string | null
  display_name: string
  kind: "user" | "org"
  role?: "self" | "read" | "write" | "admin" | "owner" | null
}

export type kind = "user" | "org"

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type Body_projects_post_project_dataset_upload = {
  path: string
  title: string
  description: string
  file: Blob | File
}

export type Body_projects_post_project_figure = {
  path: string
  title: string
  description: string
  stage?: string | null
  file?: (Blob | File) | null
}

export type Body_projects_post_project_overleaf_publication = {
  path: string
  kind:
    | "journal-article"
    | "conference-paper"
    | "report"
    | "book"
    | "masters-thesis"
    | "phd-thesis"
    | "other"
  overleaf_project_url?: string | null
  title?: string | null
  description?: string | null
  target_path?: string | null
  stage_name?: string | null
  environment_name?: string | null
  overleaf_token?: string | null
  auto_build?: boolean | null
  file?: (Blob | File) | null
}

export type kind2 =
  | "journal-article"
  | "conference-paper"
  | "report"
  | "book"
  | "masters-thesis"
  | "phd-thesis"
  | "other"

export type Body_projects_post_project_publication = {
  path: string
  kind:
    | "journal-article"
    | "conference-paper"
    | "presentation"
    | "poster"
    | "report"
    | "book"
  title: string
  description?: string | null
  stage?: string | null
  template?: string | null
  environment?: string | null
  file?: (Blob | File) | null
}

export type kind3 =
  | "journal-article"
  | "conference-paper"
  | "presentation"
  | "poster"
  | "report"
  | "book"

export type Body_projects_put_project_contents = {
  file: Blob | File
  message?: string | null
}

export type Collaborator = {
  user_id?: string | null
  github_username?: string | null
  account_name?: string | null
  full_name?: string | null
  email?: string | null
  access_level: string
}

/**
 * Portable anchor for a highlighted region within an artifact.
 *
 * Currently used for PDF text highlights (react-pdf-highlighter format).
 * ``position`` and ``content`` are kept as free-form dicts so the schema
 * can accommodate future anchor types (image regions, notebook cells, etc.)
 * without a migration.
 */
export type CommentHighlight = {
  position: {
    [key: string]: unknown
  }
  content?: {
    [key: string]: unknown
  }
}

export type CommentReply = {
  body: string
}

export type ConnectedAccounts = {
  github: boolean
  zenodo: boolean
  overleaf: boolean
  google: boolean
  zotero: boolean
}

export type ContentPatch = {
  kind:
    | "figure"
    | "dataset"
    | "publication"
    | "environment"
    | "references"
    | null
  attrs?: {
    [key: string]: unknown
  }
}

export type ContentsItem = {
  name: string
  path: string
  type: string | null
  size: number | null
  in_repo: boolean
  content?: string | null
  url?: string | null
  calkit_object?: {
    [key: string]: unknown
  } | null
  lock?: ItemLock | null
  storage?: "git" | "dvc" | "dvc-zip" | null
  stage?: string | null
  dir_items?: Array<_ContentsItemBase> | null
}

export type Dataset = {
  path: string
  imported_from?: string | null
  title?: string | null
  tabular?: boolean | null
  stage?: string | null
  description?: string | null
  url?: string | null
  id?: string
  project_id: string
}

export type DatasetForImport = {
  path: string
  imported_from?: string | null
  title?: string | null
  tabular?: boolean | null
  stage?: string | null
  description?: string | null
  url?: string | null
  dvc_import?: DVCImport | null
  git_import?: GitImport | null
  git_rev: string
}

export type DatasetResponse = {
  project: ProjectPublic
  path: string
  title: string | null
  description: string | null
  imported_from: string | null
}

export type DatasetsResponse = {
  data: Array<DatasetResponse>
  count: number
}

export type DeviceAuthorizeRequest = {
  device_code: string
}

export type DeviceAuthRequest = {
  hostname?: string | null
}

export type DeviceAuthResponse = {
  device_code: string
  verification_uri: string
  expires_in: number
  interval: number
}

export type DeviceTokenPendingResponse = {
  detail: string
}

export type DeviceTokenRequest = {
  device_code: string
}

export type DiscountCode = {
  id?: string
  created?: string
  created_by_user_id: string
  created_for_account_id?: string | null
  valid_from?: string | null
  valid_until?: string | null
  plan_id: number
  price: number
  months: number
  n_users?: number
  redeemed?: string | null
  redeemed_by_user_id?: string | null
}

export type DiscountCodePost = {
  valid_from?: string | null
  valid_until?: string | null
  created_for_account_name?: string | null
  n_users?: number
  plan_name: "standard" | "professional"
  price: number
  months: number
}

export type plan_name = "standard" | "professional"

export type DiscountCodePublic = {
  id: string
  is_valid?: boolean
  reason?: string | null
  n_users?: number | null
  price?: number | null
  months?: number | null
  plan_name?: string | null
}

export type DvcForeachStage = {
  foreach: Array<string> | string
  do: DvcPipelineStage
}

/**
 * The necessary information to import a DVC object, which can be saved to
 * a .dvc file.
 *
 * For example:
 *
 * outs:
 * - md5: 46ce259ab949ecb23751eb88ec753ff2
 * size: 83344240
 * hash: md5
 * path: time-ave-profiles.h5
 * remote: calkit:petebachant/boundary-layer-turbulence-modeling
 * push: false
 *
 * Note this is different from the file that would be produced by
 * ``dvc import``, since they bundle in Git repo information to fetch from
 * the original project's remote.
 */
export type DVCImport = {
  outs: Array<DVCOut>
}

export type DVCOut = {
  md5: string
  size: number
  hash?: string
  path: string
  remote: string
  push?: boolean
}

export type DvcPipelineStage = {
  cmd: string
  deps?: Array<string> | null
  outs?: Array<
    | string
    | {
        [key: string]: {
          [key: string]: unknown
        }
      }
  > | null
  desc?: string | null
  meta?: {
    [key: string]: unknown
  } | null
  wdir?: string | null
}

export type Environment = {
  name: string
  kind: string
  path?: string | null
  description?: string | null
  imported_from?: string | null
  all_attrs: {
    [key: string]: unknown
  }
  file_content?: string | null
}

export type ExistsResult = {
  exists: boolean
}

/**
 * A release declared as published to an external venue.
 *
 * Recorded loosely in ``calkit.yaml`` (not hosted by Calkit); used to track
 * that an artifact was, e.g., posted to arXiv or published in a journal. The
 * ``publisher`` key matches what Zenodo releases already write.
 */
export type ExternalReleasePost = {
  name: string
  kind?: string
  path?: string | null
  publisher?: string | null
  url?: string | null
  doi?: string | null
  date?: string | null
  description?: string | null
  public?: boolean
}

export type ExternalTokenResponse = {
  access_token: string
}

/**
 * Vote tally for a feature plus whether the current user has voted.
 */
export type FeatureVoteStatus = {
  feature: string
  count: number
  has_voted: boolean
}

export type Figure = {
  path: string
  title: string
  description?: string | null
  stage?: string | null
  stage_status?: StageStatus | null
  dataset?: string | null
  content?: string | null
  url?: string | null
  comment_count?: number
  storage?: "git" | "dvc" | "dvc-zip" | null
}

export type FileLock = {
  project_id: string
  path: string
  created?: string
  user_id: string
  readonly user_github_username: string | null
  readonly user_email: string
}

export type FileLockPost = {
  path: string
}

export type FsListResult = {
  paths:
    | Array<string>
    | Array<{
        [key: string]: unknown
      }>
}

export type FsOpBatchRequest = {
  operation: "exists" | "info"
  paths: Array<string>
  include?: Array<"exists" | "info" | "content"> | null
}

export type operation = "exists" | "info"

export type FsOpBatchResponse = {
  backend: "gcs" | "s3" | "google-drive" | "box" | "hf"
  results: {
    [key: string]: FsOpBatchResult
  }
}

export type backend = "gcs" | "s3" | "google-drive" | "box" | "hf"

/**
 * Result for batch file system operations on multiple paths.
 */
export type FsOpBatchResult = {
  exists?: boolean | null
  info?: {
    [key: string]: unknown
  } | null
  content_base64?: string | null
}

export type FsOpRequest = {
  operation: "get" | "put" | "exists" | "list" | "find" | "info"
  path: string
  content_length?: number | null
  content_type?: string | null
  detail?: boolean
}

export type operation2 = "get" | "put" | "exists" | "list" | "find" | "info"

/**
 * Response describing how to perform a file system operation
 * (get/put/exists/list) for a given path within the project.
 */
export type FsOpResponse = {
  backend: "gcs" | "s3" | "google-drive" | "box" | "hf"
  access?:
    | (
        | PresignedUrlAccess
        | PresignedMultipartAccess
        | PresignedChunkedAccess
        | HttpRequestAccess
        | SftpAccess
      )
    | null
  result?: FsListResult | ExistsResult | InfoResult | OperationResult | null
}

export type GitHubInstallations = {
  total_count: number
  installations: Array<{
    [key: string]: unknown
  }>
}

export type GitHubRelease = {
  url: string
  name: string
  tag_name: string
  body: string
  created: string
  published: string
}

export type GitHubReleasePost = {
  tag_name: string
  target_committish?: string
  name?: string | null
  body: string
  generate_release_notes?: boolean
}

export type GitImport = {
  files: Array<string>
}

export type GitItem = {
  name: string
  path: string
  sha: string
  size: number
  url: string
  html_url: string
  git_url: string
  download_url: string | null
  type: string
}

export type GitItemWithContents = {
  name: string
  path: string
  sha: string
  size: number
  url: string
  html_url: string
  git_url: string
  download_url: string | null
  type: string
  encoding: string
  content: string
}

/**
 * Represents a Git reference (commit, tag, or branch).
 */
export type GitRef = {
  name: string
  kind: "branch" | "tag" | "commit"
  message?: string | null
  author?: string | null
  timestamp?: string | null
  hash?: string | null
  short_hash?: string | null
  is_default?: boolean
  ahead?: number
  behind?: number
}

export type kind4 = "branch" | "tag" | "commit"

export type GitRemoteHead = {
  branch: string
  sha: string | null
}

export type HttpRequestAccess = {
  kind?: "http-request"
  url: string
  http_method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE"
  headers?: {
    [key: string]: unknown
  } | null
  params?: {
    [key: string]: unknown
  } | null
  expires_at?: string | null
}

export type http_method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE"

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ImportInfo = {
  project_owner: string
  project_name: string
  git_rev?: string | null
  path: string
}

export type InfoResult = {
  name: string
  size: number
  type: string
  time_modified?: string | null
}

export type Issue = {
  id: number
  number: number
  url: string
  user_github_username: string
  state: "open" | "closed"
  title: string
  body: string | null
  artifact_type?: string | null
  artifact_path?: string | null
}

export type state = "open" | "closed"

export type IssuePatch = {
  state: "open" | "closed"
}

export type IssuePost = {
  title: string
  body?: string | null
}

export type ItemLock = {
  created: string
  user_id: string
  user_email: string
  user_github_username: string
}

export type LabelDatasetPost = {
  imported_from?: string | null
  path: string
  title?: string | null
  tabular?: boolean | null
  stage?: string | null
  description?: string | null
}

export type Message = {
  message: string
}

export type NativeCollaboratorPost = {
  email: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type Notebook = {
  path: string
  title?: string | null
  description?: string | null
  stage?: string | null
  output_format?: "html" | "notebook" | null
  url?: string | null
  content?: string | null
  storage?: "git" | "dvc" | "dvc-zip" | null
}

/**
 * In-app notification delivered to a user when a comment is posted on
 * their project (or a project they collaborate on).
 *
 * Designed to be lightweight: no fan-out to external services here.
 * ``link`` stores a frontend URL (e.g., ``/owner/project/publications?path=…``)
 * so the notification can deep-link directly to the relevant item.
 */
export type Notification = {
  id?: string
  user_id: string
  project_id: string
  project_comment_id?: string | null
  message: string
  link: string
  read?: string | null
  created?: string
}

export type OAuthCodeExchange = {
  code: string
  redirect_uri: string
}

/**
 * Result for file operations like delete, move, copy.
 */
export type OperationResult = {
  success: boolean
  message?: string | null
}

export type OrgMemberPost = {
  username: string
  role: "read" | "write" | "admin" | "owner"
}

export type role = "read" | "write" | "admin" | "owner"

export type OrgPost = {
  name?: string | null
  display_name?: string | null
  github_name: string
}

export type OrgPublic = {
  id: string
  name: string
  display_name: string
  github_name: string
  role: string
}

export type OrgsResponse = {
  data: Array<OrgPublic>
  count: number
}

export type OrgSubscription = {
  id?: string
  created?: string
  period_months: number
  price: number
  paid_until?: string | null
  plan_id: number
  is_active?: boolean
  processor?: string | null
  processor_product_id?: string | null
  processor_price_id?: string | null
  processor_subscription_id?: string | null
  org_id: string
  n_users: number
  subscriber_user_id: string
  readonly plan_name: string
}

export type OrgSubscriptionUpdate = {
  plan_name: "standard" | "professional"
  period: "monthly" | "annual"
  discount_code?: string | null
  n_users: number
}

export type period = "monthly" | "annual"

export type OrgUserPublic = {
  name: string
  github_name: string
  role: string
}

export type OverleafSyncPost = {
  path: string
}

export type OverleafSyncResponse = {
  commits_from_overleaf: number
  overleaf_commit: string
  project_commit: string
  committed_overleaf: boolean
  committed_project: boolean
}

export type Pipeline = {
  mermaid: string
  dvc_stages: {
    [key: string]: DvcPipelineStage | DvcForeachStage
  }
  dvc_yaml: string
  calkit_yaml: string | null
  stage_statuses?: {
    [key: string]: StageStatus
  }
  status?: "up-to-date" | "stale" | "unknown"
}

export type status = "up-to-date" | "stale" | "unknown"

export type Presentation = {
  path: string
  title: string
  description?: string | null
  type?: "slides" | "poster" | "talk" | null
  stage?: string | null
  content?: string | null
  stage_info?: DvcPipelineStage | null
  url?: string | null
  storage?: "git" | "dvc" | "dvc-zip" | null
}

export type PresignedChunkedAccess = {
  kind?: "presigned-chunked"
  init_url: string
  http_method: "POST" | "PUT"
  chunk_size_bytes: number
  estimated_chunk_count: number
  upload_size_bytes: number
  content_type?: string | null
  headers?: {
    [key: string]: unknown
  } | null
  params?: {
    [key: string]: unknown
  } | null
  expires_at?: string | null
}

export type http_method2 = "POST" | "PUT"

export type PresignedMultipartAccess = {
  kind?: "presigned-multipart"
  bucket: string
  key: string
  upload_id: string
  part_urls: Array<string>
  complete_url: string
  abort_url: string
  part_size_bytes: number
  estimated_part_count: number
  upload_size_bytes: number
  content_type?: string | null
}

export type PresignedUrlAccess = {
  kind?: "presigned-url"
  url: string
  http_method: "GET" | "PUT" | "DELETE"
  expires_at?: string | null
  headers?: {
    [key: string]: unknown
  } | null
  params?: {
    [key: string]: unknown
  } | null
}

export type http_method3 = "GET" | "PUT" | "DELETE"

export type ProjectApp = {
  path?: string | null
  url?: string | null
  title?: string | null
  description?: string | null
}

/**
 * A unified comment on any project artifact or on the project itself.
 *
 * ``artifact_type`` is one of 'figure', 'publication', 'notebook', 'file',
 * or None for a project-level comment. ``artifact_path`` is the repo-relative
 * path of the artifact (None for project-level comments).
 *
 * ``highlight`` carries a portable anchor position and is only populated for
 * comments tied to a specific region (e.g., a PDF text selection). See
 * ``CommentHighlight`` for the schema.
 *
 * ``parent_id`` enables flat one-level threading: replies point to the
 * top-level comment. No nested replies are stored beyond one level in the UI,
 * though the schema permits it for future use.
 */
export type ProjectComment = {
  id?: string
  project_id: string
  user_id: string
  created?: string
  updated?: string
  comment: string
  artifact_path?: string | null
  artifact_type?: string | null
  highlight?: {
    [key: string]: unknown
  } | null
  parent_id?: string | null
  external_url?: string | null
  resolved?: string | null
  git_ref?: string | null
  git_rev?: string | null
  readonly user_github_username: string | null
  readonly user_full_name: string | null
  readonly user_email: string
}

export type ProjectCommentPatch = {
  resolved: boolean
}

export type ProjectCommentPost = {
  comment: string
  artifact_path?: string | null
  artifact_type?: string | null
  highlight?: CommentHighlight | null
  create_github_issue?: boolean
  parent_id?: string | null
  git_ref?: string | null
}

export type ProjectInvitationCreated = {
  id: string
  name?: string | null
  email?: string | null
  role_name: string
  created: string
  expires: string | null
  max_uses: number | null
  use_count: number
  revoked: boolean
  token: string
  url: string
  emailed?: boolean
}

export type ProjectInvitationPost = {
  role?: "read" | "write"
  expires_days?: number | null
  max_uses?: number | null
  name?: string | null
  email?: string | null
}

export type role2 = "read" | "write"

export type ProjectInvitationPublic = {
  id: string
  name?: string | null
  email?: string | null
  role_name: string
  created: string
  expires: string | null
  max_uses: number | null
  use_count: number
  revoked: boolean
}

export type ProjectInvitationRedeemed = {
  owner_name: string
  project_name: string
  role_name: string
}

export type ProjectOptionalExtended = {
  name: string
  title: string
  description?: string | null
  is_public?: boolean
  created?: string | null
  updated?: string | null
  git_repo_url: string
  latest_git_rev?: string | null
  status?: string | null
  status_updated?: string | null
  status_message?: string | null
  id: string
  owner_account_id: string
  owner_account_name: string
  owner_account_display_name: string
  owner_account_type: string
  current_user_access?: "read" | "write" | "admin" | "owner" | null
  calkit_info_keys?: Array<string> | null
  readme_content?: string | null
}

export type ProjectPatch = {
  title?: string | null
  description?: string | null
  is_public?: boolean | null
}

export type ProjectPost = {
  name: string
  title: string
  description?: string | null
  is_public?: boolean
  created?: string | null
  updated?: string | null
  git_repo_url?: string | null
  latest_git_rev?: string | null
  status?: string | null
  status_updated?: string | null
  status_message?: string | null
  template?: string | null
  git_repo_exists?: boolean | null
}

export type ProjectPublic = {
  name: string
  title: string
  description?: string | null
  is_public?: boolean
  created?: string | null
  updated?: string | null
  git_repo_url: string
  latest_git_rev?: string | null
  status?: string | null
  status_updated?: string | null
  status_message?: string | null
  id: string
  owner_account_id: string
  owner_account_name: string
  owner_account_display_name: string
  owner_account_type: string
  current_user_access?: "read" | "write" | "admin" | "owner" | null
}

export type ProjectsPublic = {
  data: Array<ProjectPublic>
  count: number
}

export type ProjectStatus = {
  timestamp: string
  status: "in-progress" | "on-hold" | "completed"
  message?: string | null
}

export type status2 = "in-progress" | "on-hold" | "completed"

export type ProjectStatusPost = {
  status: "in-progress" | "on-hold" | "completed"
  message?: string | null
}

export type Publication = {
  path: string
  title: string
  description?: string | null
  type?:
    | "journal-article"
    | "conference-paper"
    | "presentation"
    | "poster"
    | "report"
    | "book"
    | null
  stage?: string | null
  stage_status?: StageStatus | null
  content?: string | null
  stage_info?: DvcPipelineStage | null
  url?: string | null
  overleaf?: PublicationOverleaf | null
  storage?: "git" | "dvc" | "dvc-zip" | null
}

export type PublicationOverleaf = {
  project_id: string
  wdir?: string | null
  url?: string | null
  push_paths?: Array<string>
  sync_paths?: Array<string>
  last_sync_commit?: string | null
}

export type Question = {
  id?: string
  project_id: string
  number: number
  question: string
}

export type QuestionEvidence = {
  kind: "figure" | "result" | "publication"
  path: string
  key?: string | null
  explanation?: string | null
  figure?: Figure | null
  result?: Result | null
  publication?: Publication | null
  value?: string | null
}

export type kind5 = "figure" | "result" | "publication"

export type QuestionEvidencePost = {
  kind: "figure" | "result" | "publication"
  path: string
  key?: string | null
  explanation?: string | null
}

export type QuestionPost = {
  question: string
}

export type QuestionPublic = {
  id: string
  project_id: string
  number: number
  question: string
  hypothesis?: string | null
  answer?: string | null
  evidence?: Array<QuestionEvidence>
}

export type QuestionPut = {
  question?: string | null
  hypothesis?: string | null
  answer?: string | null
  evidence?: Array<QuestionEvidencePost>
}

export type ReferenceEntry = {
  type: string
  key: string
  file_path?: string | null
  url?: string | null
  attrs: {
    [key: string]: unknown
  }
  zotero_item_key?: string | null
  has_pdf?: boolean
  note_count?: number
}

export type ReferenceFile = {
  path: string
  key: string
}

export type ReferenceItemPost = {
  path: string
  type?: string
  key: string
  fields?: {
    [key: string]: string
  }
}

export type ReferenceItemPut = {
  path: string
  type: string
  key: string
  fields?: {
    [key: string]: string
  }
}

export type ReferenceNote = {
  text: string
  highlight?: ReferenceNoteHighlight | null
}

export type ReferenceNoteHighlight = {
  position: {
    [key: string]: unknown
  }
  quote?: string
}

export type ReferenceNotesPut = {
  path: string
  notes: Array<ReferenceNote>
}

export type ReferenceNotesResponse = {
  notes: Array<ReferenceNote>
}

export type References = {
  path: string
  files?: Array<ReferenceFile> | null
  entries?: Array<ReferenceEntry> | null
  imported_from?: ImportInfo | null
  raw_text?: string | null
  zotero?: ReferenceZoteroLink | null
  stages?: Array<string> | null
}

export type ReferencesPost = {
  path: string
  label_existing?: boolean
}

export type ReferenceZoteroLink = {
  library_type: "user" | "group"
  library_id: string
  collection_key: string
  collection_name?: string | null
  last_sync_version?: number | null
  last_synced?: string | null
}

export type library_type = "user" | "group"

export type RefreshTokenRequest = {
  refresh_token: string
}

export type ReleaseCommentPost = {
  comment: string
  author_name?: string | null
  highlight?: CommentHighlight | null
  parent_id?: string | null
}

export type ReleaseCommentPublic = {
  id: string
  author_name: string | null
  comment: string
  highlight?: {
    [key: string]: unknown
  } | null
  external_url: string | null
  parent_id?: string | null
  resolved?: string | null
  created: string
}

export type ReleaseCommentResolvePost = {
  resolved: boolean
}

/**
 * Result of creating (or finding) a GitHub release for a Calkit release.
 */
export type ReleaseGithubResult = {
  url: string
  created: boolean
}

/**
 * A release row for the project releases page.
 *
 * Merges two sources: ``calkit`` releases declared in ``calkit.yaml`` (the
 * public, DOI-bearing ones produced via the CLI/Zenodo) and ``cloud``
 * releases stored in this database (the private, secret-link ones). Fields
 * that only apply to one source are optional.
 */
export type ReleaseListItem = {
  source: "cloud" | "calkit"
  name: string
  kind?: string | null
  path?: string | null
  description?: string | null
  git_ref?: string | null
  git_rev?: string | null
  git_rev_abbrev?: string | null
  public?: boolean
  url?: string | null
  doi?: string | null
  publisher?: string | null
  date?: string | null
  internal?: boolean
  view_count?: number | null
  comment_count?: number | null
  share_count?: number | null
  github_release_url?: string | null
}

export type source = "cloud" | "calkit"

export type ReleasePost = {
  name: string
  kind?: string
  path?: string | null
  description?: string | null
  git_ref?: string | null
  public?: boolean
  acknowledge_non_reproducible?: boolean
}

/**
 * Release as seen by a user with write access.
 */
export type ReleasePublic = {
  name: string
  kind?: string
  path?: string | null
  description?: string | null
  git_ref?: string | null
  git_rev?: string | null
  public?: boolean
  url?: string | null
  doi?: string | null
  id: string
  project_id: string
  view_count: number
  comment_count: number
  git_rev_abbrev: string | null
  created: string
}

/**
 * Returned once when a token is minted; carries the raw token to share.
 */
export type ReleaseShareTokenCreated = {
  id: string
  email: string | null
  permission: string
  note: string | null
  expires_at: string | null
  revoked: boolean
  view_count: number
  created: string
  token: string
  email_sent?: boolean
}

export type ReleaseShareTokenPost = {
  email?: string | null
  permission?: "view" | "comment"
  note?: string | null
  expires_at?: string | null
}

export type permission = "view" | "comment"

/**
 * A share token as shown in the manage list -- never includes the secret.
 */
export type ReleaseShareTokenPublic = {
  id: string
  email: string | null
  permission: string
  note: string | null
  expires_at: string | null
  revoked: boolean
  view_count: number
  created: string
}

/**
 * Whether the pipeline stage that produces a release path is up-to-date.
 *
 * Used to warn before creating a release of a possibly non-reproducible
 * artifact. ``stage`` is None when the path isn't produced by any pipeline
 * stage (staleness doesn't apply), in which case ``up_to_date`` stays True.
 */
export type ReleaseStaleness = {
  path?: string | null
  stage?: string | null
  status?:
    | "up-to-date"
    | "stale"
    | "not-run"
    | "unknown"
    | "always-run"
    | "frozen"
    | null
  up_to_date?: boolean
  modified_inputs?: Array<string>
  modified_outputs?: Array<string>
  missing_outputs?: Array<string>
}

/**
 * Request to look up an already-published release from a URL or DOI.
 */
export type ReleaseUrlImport = {
  url: string
}

/**
 * Metadata parsed from an external release URL/DOI.
 *
 * Returned by the parse-url lookup so the create modal can pre-fill the
 * declare-external form. The user reviews/edits it, then submits via the
 * external release endpoint. ``git_rev`` is intentionally absent -- imports
 * can't know the producing commit, so it's left for the user to set later.
 */
export type ReleaseUrlMetadata = {
  publisher?: string | null
  title?: string | null
  doi?: string | null
  url?: string | null
  date?: string | null
  description?: string | null
  kind?: string
}

/**
 * Release as rendered on its page, for a member or a share-token holder.
 *
 * Deliberately omits internal identifiers; exposes only what the viewer page
 * needs to render the artifact, the provenance note, and comments. The
 * viewer's effective ``permission`` says whether they may comment or manage
 * the release, so the UI can adapt without leaking the share tokens.
 */
export type ReleaseView = {
  name: string
  kind: string
  path: string | null
  description: string | null
  git_ref: string | null
  git_rev_abbrev: string | null
  public: boolean
  comment_count: number
  created: string
  owner_account_name: string
  owner_account_display_name: string
  project_name: string
  project_title: string
  permission: "view" | "comment" | "manage"
  viewer_email?: string | null
}

export type permission2 = "view" | "comment" | "manage"

export type ReproCheck = {
  has_pipeline: boolean
  has_readme: boolean
  instructions_in_readme: boolean
  is_dvc_repo: boolean
  is_git_repo: boolean
  has_calkit_info: boolean
  has_dev_container: boolean
  n_environments: number
  n_stages: number
  stages_with_env: Array<string>
  stages_without_env: Array<string>
  n_datasets: number
  n_datasets_no_import_or_stage: number
  n_figures: number
  n_figures_no_import_or_stage: number
  n_publications: number
  n_publications_no_import_or_stage: number
  n_dvc_remotes: number
  /**
   * Formulate a recommendation for the project.
   */
  readonly recommendation: string | null
  readonly n_datasets_with_import_or_stage: number
  readonly n_figures_with_import_or_stage: number
  readonly n_publications_with_import_or_stage: number
  readonly n_stages_without_env: number
  readonly n_stages_with_env: number
}

export type Result = {
  path: string
  title: string
  description?: string | null
  stage?: string | null
}

export type SearchResultItem = {
  kind: "project" | "org" | "dataset"
  name: string
  title?: string | null
  description?: string | null
  owner_name?: string | null
  project_name?: string | null
}

export type kind6 = "project" | "org" | "dataset"

export type SearchResults = {
  results: Array<SearchResultItem>
}

export type SftpAccess = {
  kind?: "sftp"
  host: string
  port?: number
  username: string
  password?: string | null
  private_key?: string | null
  remote_path: string
  expires_at?: string | null
}

export type Showcase = {
  elements: Array<
    | ShowcaseFigure
    | ShowcasePublication
    | ShowcaseText
    | ShowcaseMarkdown
    | ShowcaseYaml
    | ShowcaseNotebook
  >
}

export type ShowcaseFigure = {
  figure: Figure
}

export type ShowcaseMarkdown = {
  markdown: string
}

export type ShowcaseNotebook = {
  notebook: Notebook
}

export type ShowcasePublication = {
  publication: Publication
}

export type ShowcaseText = {
  text: string
}

export type ShowcaseYaml = {
  yaml: string
}

export type Software = {
  items: Array<SoftwareItem>
}

export type SoftwareItem = {
  title: string
  path: string
  description?: string | null
}

export type StageStatus = {
  status:
    | "up-to-date"
    | "stale"
    | "not-run"
    | "unknown"
    | "always-run"
    | "frozen"
  modified_command?: boolean
  modified_inputs?: Array<string>
  modified_outputs?: Array<string>
  missing_outputs?: Array<string>
}

export type status3 =
  | "up-to-date"
  | "stale"
  | "not-run"
  | "unknown"
  | "always-run"
  | "frozen"

export type StorageUsage = {
  limit_gb: number
  used_gb: number
}

export type SubscriptionPlan = {
  name: string
  id: number
  price: number
  private_projects_limit: number | null
  storage_limit: number
  annual_discount_factor?: number
}

export type SubscriptionUpdate = {
  plan_name: "free" | "standard" | "professional"
  period: "monthly" | "annual"
  discount_code?: string | null
}

export type plan_name2 = "free" | "standard" | "professional"

export type Token = {
  access_token: string
  token_type?: string
  expires_in?: number | null
  refresh_token?: string | null
}

export type TokenPatch = {
  is_active: boolean
}

export type TokenPost = {
  expires_days: number
  scope: "dvc" | null
  description?: string | null
}

export type TokenPut = {
  token: string
  expires?: string | null
}

export type TokenResp = {
  access_token: string
  token_type?: string
  expires_in?: number | null
  refresh_token?: string | null
  id?: string
  user_id: string
  scope?: string | null
  created?: string
  updated?: string
  expires: string
  is_active: boolean
  description?: string | null
  last_used?: string | null
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UpdateSubscriptionResponse = {
  subscription: UserSubscription | OrgSubscription
  stripe_session_client_secret: string | null
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
  account_name?: string | null
  github_username?: string | null
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
  github_username: string | null
  subscription: UserSubscription | null
}

export type UserRegister = {
  email: string
  password: string
  account_name?: string | null
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserSubscription = {
  id?: string
  created?: string
  period_months: number
  price: number
  paid_until?: string | null
  plan_id: number
  is_active?: boolean
  processor?: string | null
  processor_product_id?: string | null
  processor_price_id?: string | null
  processor_subscription_id?: string | null
  user_id: string
  readonly plan_name: string
}

export type UserTokenPublic = {
  id?: string
  user_id: string
  scope?: string | null
  created?: string
  updated?: string
  expires: string
  is_active: boolean
  description?: string | null
  last_used?: string | null
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
  github_username?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ZoteroAuthFinish = {
  oauth_token: string
  oauth_verifier: string
}

export type ZoteroAuthStart = {
  authorize_url: string
}

export type ZoteroCollection = {
  collection_key: string
  collection_name?: string | null
  parent_collection?: string | null
}

export type ZoteroImportPost = {
  library_type: "user" | "group"
  library_id: string
  collection_key?: string | null
  item_keys?: Array<string> | null
  bib_path?: string
  overwrite?: boolean
}

export type ZoteroItem = {
  item_key: string
  title?: string | null
  item_type?: string | null
  year?: string | null
  first_author?: string | null
}

export type ZoteroLibrary = {
  library_type: "user" | "group"
  library_id: string
  name: string
}

export type ZoteroSyncPost = {
  path: string
}

export type ZoteroSyncResponse = {
  path: string
  last_sync_version: number
  last_synced: string
  committed: boolean
}

export type GetAccountData = {
  accountName: string
}

export type GetAccountResponse = AccountPublic

export type GetDatasetsData = {
  includeImported?: boolean
  limit?: number
  offset?: number
  searchFor?: string | null
}

export type GetDatasetsResponse = DatasetsResponse

export type MetricsResponse = unknown

export type GetFeatureVoteStatusData = {
  feature: string
}

export type GetFeatureVoteStatusResponse = FeatureVoteStatus

export type PostFeatureVoteData = {
  feature: string
}

export type PostFeatureVoteResponse = FeatureVoteStatus

export type DeleteFeatureVoteData = {
  feature: string
}

export type DeleteFeatureVoteResponse = FeatureVoteStatus

export type LoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginAccessTokenResponse = Token

export type TestTokenResponse = UserPublic

export type RefreshAccessTokenData = {
  requestBody: RefreshTokenRequest
}

export type RefreshAccessTokenResponse = Token

export type RecoverPasswordData = {
  email: string
}

export type RecoverPasswordResponse = Message

export type ResetPasswordData = {
  requestBody: NewPassword
}

export type ResetPasswordResponse = Message

export type RecoverPasswordHtmlContentData = {
  email: string
}

export type RecoverPasswordHtmlContentResponse = string

export type LoginWithGithubData = {
  requestBody: OAuthCodeExchange
}

export type LoginWithGithubResponse = Token

export type LoginWithGoogleData = {
  requestBody: OAuthCodeExchange
}

export type LoginWithGoogleResponse = Token

export type LoginWithGithubOidcData = {
  authorization?: string | null
}

export type LoginWithGithubOidcResponse = Token

export type LoginWithGithubTokenData = {
  authorization?: string | null
}

export type LoginWithGithubTokenResponse = Token

export type PostLoginDeviceData = {
  requestBody?: DeviceAuthRequest | null
}

export type PostLoginDeviceResponse = DeviceAuthResponse

export type PostLoginDeviceAuthorizeData = {
  requestBody: DeviceAuthorizeRequest
}

export type PostLoginDeviceAuthorizeResponse = Message

export type PostLoginDeviceTokenData = {
  requestBody: DeviceTokenRequest
}

export type PostLoginDeviceTokenResponse =
  | (Token | DeviceTokenPendingResponse)
  | DeviceTokenPendingResponse

export type TestEmailData = {
  emailTo: string
}

export type TestEmailResponse = Message

export type GetDiscountCodeData = {
  discountCode: string
  nUsers?: number
}

export type GetDiscountCodeResponse = DiscountCodePublic

export type PostDiscountCodeData = {
  requestBody: DiscountCodePost
}

export type PostDiscountCodeResponse = DiscountCode

export type GetSubscriptionPlansResponse = Array<SubscriptionPlan>

export type GlobalSearchData = {
  limit?: number
  q: string
}

export type GlobalSearchResponse = SearchResults

export type GetNotificationsData = {
  unreadOnly?: boolean
}

export type GetNotificationsResponse = Array<Notification>

export type MarkNotificationReadData = {
  notificationId: string
}

export type MarkNotificationReadResponse = Notification

export type MarkAllNotificationsReadResponse = void

export type GetUserOrgsResponse = Array<OrgPublic>

export type GetOrgsData = {
  limit?: number
  offset?: number
  searchFor?: string | null
}

export type GetOrgsResponse = OrgsResponse

export type PostOrgData = {
  requestBody: OrgPost
}

export type PostOrgResponse = OrgPublic

export type AddOrgMemberData = {
  orgName: string
  requestBody: OrgMemberPost
}

export type AddOrgMemberResponse = Message

export type PutOrgSubscriptionData = {
  orgName: string
  requestBody: OrgSubscriptionUpdate
}

export type PutOrgSubscriptionResponse = UpdateSubscriptionResponse

export type GetOrgStorageData = {
  orgName: string
}

export type GetOrgStorageResponse = StorageUsage

export type GetOrgUsersData = {
  orgName: string
}

export type GetOrgUsersResponse = Array<OrgUserPublic>

export type GetProjectsData = {
  limit?: number
  offset?: number
  ownerName?: string | null
  searchFor?: string | null
}

export type GetProjectsResponse = ProjectsPublic

export type PostProjectData = {
  requestBody: ProjectPost
}

export type PostProjectResponse = ProjectPublic

export type GetOwnedProjectsData = {
  limit?: number
  offset?: number
  searchFor?: string | null
}

export type GetOwnedProjectsResponse = ProjectsPublic

export type GetProjectData = {
  getExtendedInfo?: boolean
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectResponse = ProjectOptionalExtended

export type PatchProjectData = {
  ownerName: string
  projectName: string
  requestBody: ProjectPatch
}

export type PatchProjectResponse = ProjectPublic

export type DeleteProjectData = {
  ownerName: string
  projectName: string
}

export type DeleteProjectResponse = Message

export type DeleteProjectByIdData = {
  projectId: string
}

export type DeleteProjectByIdResponse = Message

export type GetProjectGitRepoData = {
  ownerName: string
  projectName: string
}

export type GetProjectGitRepoResponse = {
  [key: string]: unknown
}

export type GetProjectGitRemoteHeadData = {
  branch?: string | null
  ownerName: string
  projectName: string
}

export type GetProjectGitRemoteHeadResponse = GitRemoteHead

export type SearchProjectRefsData = {
  ownerName: string
  projectName: string
  /**
   * Search query for refs
   */
  q?: string | null
}

export type SearchProjectRefsResponse = Array<GitRef>

export type GetProjectHistoryData = {
  /**
   * Max number of commits to return
   */
  limit?: number
  /**
   * Number of commits to skip
   */
  offset?: number
  ownerName: string
  projectName: string
  /**
   * Branch, tag, or commit to read history from
   */
  ref?: string | null
}

export type GetProjectHistoryResponse = Array<{
  [key: string]: unknown
}>

export type GetProjectCommitData = {
  commitHash: string
  ownerName: string
  projectName: string
}

export type GetProjectCommitResponse = {
  [key: string]: unknown
}

export type GetProjectFileHistoryData = {
  /**
   * Max number of commits to return
   */
  limit?: number
  ownerName: string
  path: string
  projectName: string
  /**
   * Artifact storage class; when supplied, limits the lookup to relevant sources (e.g., skips the dvc.lock scan for git files).
   */
  storage?: "git" | "dvc" | "dvc-zip" | null
}

export type GetProjectFileHistoryResponse = Array<{
  [key: string]: unknown
}>

export type GetProjectGitContentsData = {
  astype?: "" | ".raw" | ".html" | ".object"
  ownerName: string
  path?: string | null
  projectName: string
  ref?: string | null
}

export type GetProjectGitContentsResponse =
  | Array<GitItem>
  | GitItemWithContents
  | string

export type GetProjectGitContents1Data = {
  astype?: "" | ".raw" | ".html" | ".object"
  ownerName: string
  path: string | null
  projectName: string
  ref?: string | null
}

export type GetProjectGitContents1Response =
  | Array<GitItem>
  | GitItemWithContents
  | string

export type GetProjectContentsData = {
  ownerName: string
  path?: string | null
  projectName: string
  ref?: string | null
  ttl?: number | null
}

export type GetProjectContentsResponse = ContentsItem

export type GetProjectContents1Data = {
  ownerName: string
  path: string | null
  projectName: string
  ref?: string | null
  ttl?: number | null
}

export type GetProjectContents1Response = ContentsItem

export type PutProjectContentsData = {
  contentLength: number
  formData: Body_projects_put_project_contents
  ownerName: string
  path: string
  projectName: string
}

export type PutProjectContentsResponse = ContentsItem

export type PatchProjectContentsData = {
  ownerName: string
  path: string
  projectName: string
  requestBody: ContentPatch
}

export type PatchProjectContentsResponse = {
  [key: string]: unknown
} | null

export type GetProjectContentPathsData = {
  ownerName: string
  projectName: string
  ref?: string | null
  ttl?: number | null
}

export type GetProjectContentPathsResponse = Array<string>

export type GetProjectQuestionsData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectQuestionsResponse = Array<QuestionPublic>

export type PostProjectQuestionData = {
  ownerName: string
  projectName: string
  requestBody: QuestionPost
}

export type PostProjectQuestionResponse = Question

export type PutProjectQuestionData = {
  number: number
  ownerName: string
  projectName: string
  requestBody: QuestionPut
}

export type PutProjectQuestionResponse = QuestionPublic

export type GetProjectFiguresData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectFiguresResponse = Array<Figure>

export type PostProjectFigureData = {
  formData: Body_projects_post_project_figure
  ownerName: string
  projectName: string
}

export type PostProjectFigureResponse = Figure

export type GetProjectResultsData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectResultsResponse = Array<Result>

export type GetProjectFigureData = {
  figurePath: string
  ownerName: string
  projectName: string
  ref?: string | null
  ttl?: number | null
}

export type GetProjectFigureResponse = Figure

export type GetProjectCommentsData = {
  artifactPath?: string | null
  artifactType?: string | null
  ownerName: string
  projectName: string
}

export type GetProjectCommentsResponse = Array<ProjectComment>

export type PostProjectCommentData = {
  ownerName: string
  projectName: string
  requestBody: ProjectCommentPost
}

export type PostProjectCommentResponse = ProjectComment

export type PatchProjectCommentData = {
  commentId: string
  ownerName: string
  projectName: string
  requestBody: ProjectCommentPatch
}

export type PatchProjectCommentResponse = ProjectComment

export type DeleteProjectCommentData = {
  commentId: string
  ownerName: string
  projectName: string
}

export type DeleteProjectCommentResponse = unknown

export type PostProjectCommentReplyData = {
  commentId: string
  ownerName: string
  projectName: string
  requestBody: CommentReply
}

export type PostProjectCommentReplyResponse = ProjectComment

export type GetProjectDatasetsData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectDatasetsResponse = Array<Dataset>

export type GetProjectDatasetData = {
  filterPaths?: Array<string> | null
  ownerName: string
  path: string
  projectName: string
  ref?: string | null
}

export type GetProjectDatasetResponse = DatasetForImport

export type PostProjectDatasetLabelData = {
  ownerName: string
  projectName: string
  requestBody: LabelDatasetPost
}

export type PostProjectDatasetLabelResponse = Dataset

export type PostProjectDatasetUploadData = {
  contentLength: number
  formData: Body_projects_post_project_dataset_upload
  ownerName: string
  projectName: string
}

export type PostProjectDatasetUploadResponse = Dataset

export type GetProjectPublicationsData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectPublicationsResponse = Array<Publication>

export type PostProjectPublicationData = {
  formData: Body_projects_post_project_publication
  ownerName: string
  projectName: string
}

export type PostProjectPublicationResponse = Publication

export type GetProjectPresentationsData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectPresentationsResponse = Array<Presentation>

export type PostProjectOverleafPublicationData = {
  formData: Body_projects_post_project_overleaf_publication
  ownerName: string
  projectName: string
}

export type PostProjectOverleafPublicationResponse = Publication

export type PostProjectOverleafSyncData = {
  ownerName: string
  projectName: string
  requestBody: OverleafSyncPost
}

export type PostProjectOverleafSyncResponse = OverleafSyncResponse

export type PostProjectSyncData = {
  ownerName: string
  projectName: string
}

export type PostProjectSyncResponse = Message

export type GetProjectPipelineData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectPipelineResponse = Pipeline | null

export type GetProjectCollaboratorsData = {
  ownerName: string
  projectName: string
}

export type GetProjectCollaboratorsResponse = Array<Collaborator>

export type PutProjectCollaboratorData = {
  githubUsername: string
  ownerName: string
  projectName: string
}

export type PutProjectCollaboratorResponse = Message

export type DeleteProjectCollaboratorData = {
  githubUsername: string
  ownerName: string
  projectName: string
}

export type DeleteProjectCollaboratorResponse = Message

export type PostProjectCollaboratorByEmailData = {
  ownerName: string
  projectName: string
  requestBody: NativeCollaboratorPost
}

export type PostProjectCollaboratorByEmailResponse = Message

export type DeleteProjectNativeCollaboratorData = {
  ownerName: string
  projectName: string
  userId: string
}

export type DeleteProjectNativeCollaboratorResponse = Message

export type PostProjectInvitationData = {
  ownerName: string
  projectName: string
  requestBody: ProjectInvitationPost
}

export type PostProjectInvitationResponse = ProjectInvitationCreated

export type GetProjectInvitationsData = {
  ownerName: string
  projectName: string
}

export type GetProjectInvitationsResponse = Array<ProjectInvitationPublic>

export type DeleteProjectInvitationData = {
  invitationId: string
  ownerName: string
  projectName: string
}

export type DeleteProjectInvitationResponse = Message

export type PostProjectInvitationRedemptionData = {
  token: string
}

export type PostProjectInvitationRedemptionResponse = ProjectInvitationRedeemed

export type GetProjectIssuesData = {
  ownerName: string
  page?: number
  perPage?: number
  projectName: string
  state?: "open" | "closed" | "all"
}

export type GetProjectIssuesResponse = Array<Issue>

export type PostProjectIssueData = {
  ownerName: string
  projectName: string
  requestBody: IssuePost
}

export type PostProjectIssueResponse = Issue

export type PatchProjectIssueData = {
  issueNumber: number
  ownerName: string
  projectName: string
  requestBody: IssuePatch
}

export type PatchProjectIssueResponse = Message

export type GetProjectReferencesData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectReferencesResponse = Array<References>

export type PostProjectReferencesData = {
  ownerName: string
  projectName: string
  requestBody: ReferencesPost
}

export type PostProjectReferencesResponse = References

export type DeleteProjectReferencesData = {
  ownerName: string
  path: string
  projectName: string
}

export type DeleteProjectReferencesResponse = Message

export type PostProjectReferenceItemData = {
  ownerName: string
  projectName: string
  requestBody: ReferenceItemPost
}

export type PostProjectReferenceItemResponse = Message

export type PutProjectReferenceItemData = {
  bibKey: string
  ownerName: string
  projectName: string
  requestBody: ReferenceItemPut
}

export type PutProjectReferenceItemResponse = Message

export type DeleteProjectReferenceItemData = {
  bibKey: string
  ownerName: string
  path: string
  projectName: string
}

export type DeleteProjectReferenceItemResponse = Message

export type GetProjectZoteroLibrariesData = {
  ownerName: string
  projectName: string
}

export type GetProjectZoteroLibrariesResponse = Array<ZoteroLibrary>

export type GetProjectZoteroCollectionsData = {
  libraryId: string
  libraryType: "user" | "group"
  ownerName: string
  projectName: string
}

export type GetProjectZoteroCollectionsResponse = Array<ZoteroCollection>

export type GetProjectZoteroItemsData = {
  collectionKey?: string | null
  libraryId: string
  libraryType: "user" | "group"
  ownerName: string
  projectName: string
  q?: string | null
}

export type GetProjectZoteroItemsResponse = Array<ZoteroItem>

export type PostProjectZoteroImportData = {
  ownerName: string
  projectName: string
  requestBody: ZoteroImportPost
}

export type PostProjectZoteroImportResponse = References

export type PostProjectZoteroSyncData = {
  ownerName: string
  projectName: string
  requestBody: ZoteroSyncPost
}

export type PostProjectZoteroSyncResponse = ZoteroSyncResponse

export type GetProjectZoteroItemPdfData = {
  bibKey: string
  index?: number
  ownerName: string
  path: string
  projectName: string
}

export type GetProjectZoteroItemPdfResponse = unknown

export type GetProjectReferenceNotesData = {
  bibKey: string
  ownerName: string
  path: string
  projectName: string
}

export type GetProjectReferenceNotesResponse = ReferenceNotesResponse

export type PutProjectReferenceNotesData = {
  bibKey: string
  ownerName: string
  projectName: string
  requestBody: ReferenceNotesPut
}

export type PutProjectReferenceNotesResponse = ReferenceNotesResponse

export type GetProjectEnvironmentsData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectEnvironmentsResponse = Array<Environment>

export type PostProjectEnvironmentData = {
  ownerName: string
  projectName: string
  ref?: string | null
  requestBody: Environment
}

export type PostProjectEnvironmentResponse = Environment

export type GetProjectSoftwareData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectSoftwareResponse = Software

export type GetProjectFileLocksData = {
  ownerName: string
  projectName: string
}

export type GetProjectFileLocksResponse = Array<FileLock>

export type PostProjectFileLockData = {
  ownerName: string
  projectName: string
  requestBody: FileLockPost
}

export type PostProjectFileLockResponse = FileLock

export type DeleteProjectFileLockData = {
  ownerName: string
  projectName: string
  requestBody: FileLockPost
}

export type DeleteProjectFileLockResponse = Message

export type GetProjectNotebooksData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectNotebooksResponse = Array<Notebook>

export type GetProjectReproCheckData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectReproCheckResponse = ReproCheck

export type PutProjectDevContainerData = {
  ownerName: string
  projectName: string
}

export type PutProjectDevContainerResponse = Message

export type GetProjectAppData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectAppResponse = ProjectApp | null

export type GetProjectShowcaseData = {
  ownerName: string
  projectName: string
  ref?: string | null
  ttl?: number | null
}

export type GetProjectShowcaseResponse = Showcase | null

export type GetProjectGithubReleasesData = {
  ownerName: string
  projectName: string
}

export type GetProjectGithubReleasesResponse = Array<GitHubRelease>

export type PostProjectGithubReleaseData = {
  ownerName: string
  projectName: string
  requestBody: GitHubReleasePost
}

export type PostProjectGithubReleaseResponse = GitHubRelease

export type PostProjectStatusData = {
  ownerName: string
  projectName: string
  requestBody: ProjectStatusPost
}

export type PostProjectStatusResponse = ProjectStatus

export type PostProjectDvcFileData = {
  idx: string
  md5: string
  ownerName: string
  projectName: string
  scope?: string | null
}

export type PostProjectDvcFileResponse = Message

export type GetProjectDvcFileData = {
  idx: string
  md5: string
  ownerName: string
  projectName: string
  scope?: string | null
}

export type GetProjectDvcFileResponse = unknown

export type PostProjectFsOpData = {
  ownerName: string
  projectName: string
  requestBody: FsOpRequest
}

export type PostProjectFsOpResponse = FsOpResponse

export type PostProjectFsBatchOpData = {
  ownerName: string
  projectName: string
  requestBody: FsOpBatchRequest
}

export type PostProjectFsBatchOpResponse = FsOpBatchResponse

export type PostProjectReleaseData = {
  ownerName: string
  projectName: string
  requestBody: ReleasePost
}

export type PostProjectReleaseResponse = ReleasePublic

export type GetProjectReleasesData = {
  ownerName: string
  projectName: string
  ref?: string | null
}

export type GetProjectReleasesResponse = Array<ReleaseListItem>

export type PostExternalReleaseData = {
  ownerName: string
  projectName: string
  requestBody: ExternalReleasePost
}

export type PostExternalReleaseResponse = Message

export type ParseReleaseUrlData = {
  ownerName: string
  projectName: string
  requestBody: ReleaseUrlImport
}

export type ParseReleaseUrlResponse = ReleaseUrlMetadata

export type ImportGithubReleasesData = {
  ownerName: string
  projectName: string
}

export type ImportGithubReleasesResponse = Message

export type GetReleaseStalenessData = {
  gitRef?: string | null
  ownerName: string
  path?: string | null
  projectName: string
}

export type GetReleaseStalenessResponse = ReleaseStaleness

export type DeleteProjectReleaseData = {
  ownerName: string
  projectName: string
  releaseName: string
}

export type DeleteProjectReleaseResponse = Message

export type CreateReleaseGithubReleaseData = {
  ownerName: string
  projectName: string
  releaseName: string
}

export type CreateReleaseGithubReleaseResponse = ReleaseGithubResult

export type CreateReleaseShareData = {
  ownerName: string
  projectName: string
  releaseName: string
  requestBody: ReleaseShareTokenPost
}

export type CreateReleaseShareResponse = ReleaseShareTokenCreated

export type ListReleaseSharesData = {
  ownerName: string
  projectName: string
  releaseName: string
}

export type ListReleaseSharesResponse = Array<ReleaseShareTokenPublic>

export type DeleteReleaseShareData = {
  ownerName: string
  projectName: string
  releaseName: string
  tokenId: string
}

export type DeleteReleaseShareResponse = Message

export type GetReleaseViewData = {
  ownerName: string
  projectName: string
  releaseName: string
  token?: string | null
}

export type GetReleaseViewResponse = ReleaseView

export type GetReleaseContentData = {
  ownerName: string
  projectName: string
  releaseName: string
  token?: string | null
}

export type GetReleaseContentResponse = ContentsItem

export type GetReleaseContentsData = {
  ownerName: string
  path?: string | null
  projectName: string
  releaseName: string
  token?: string | null
}

export type GetReleaseContentsResponse = ContentsItem

export type GetReleaseCommentsData = {
  ownerName: string
  projectName: string
  releaseName: string
  token?: string | null
}

export type GetReleaseCommentsResponse = Array<ReleaseCommentPublic>

export type PostReleaseCommentData = {
  ownerName: string
  projectName: string
  releaseName: string
  requestBody: ReleaseCommentPost
  token?: string | null
}

export type PostReleaseCommentResponse = ReleaseCommentPublic

export type ResolveReleaseCommentData = {
  commentId: string
  ownerName: string
  projectName: string
  releaseName: string
  requestBody: ReleaseCommentResolvePost
}

export type ResolveReleaseCommentResponse = ReleaseCommentPublic

export type ReadUsersData = {
  limit?: number
  skip?: number
}

export type ReadUsersResponse = UsersPublic

export type CreateUserData = {
  requestBody: UserCreate
}

export type CreateUserResponse = UserPublic

export type GetCurrentUserResponse = UserPublic

export type DeleteCurrentUserResponse = Message

export type UpdateCurrentUserData = {
  requestBody: UserUpdateMe
}

export type UpdateCurrentUserResponse = UserPublic

export type UpdateCurrentUserPasswordData = {
  requestBody: UpdatePassword
}

export type UpdateCurrentUserPasswordResponse = Message

export type RegisterUserData = {
  requestBody: UserRegister
}

export type RegisterUserResponse = UserPublic

export type ReadUserByIdData = {
  userId: string
}

export type ReadUserByIdResponse = UserPublic

export type UpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UpdateUserResponse = UserPublic

export type DeleteUserData = {
  userId: string
}

export type DeleteUserResponse = Message

export type GetUserGithubReposData = {
  page?: number
  perPage?: number
}

export type GetUserGithubReposResponse = Array<{
  [key: string]: unknown
}>

export type PutUserSubscriptionData = {
  requestBody: SubscriptionUpdate
}

export type PutUserSubscriptionResponse = UpdateSubscriptionResponse

export type GetUserTokensData = {
  isActive?: boolean | null
}

export type GetUserTokensResponse = Array<UserTokenPublic>

export type PostUserTokenData = {
  requestBody: TokenPost
}

export type PostUserTokenResponse = TokenResp

export type PatchUserTokenData = {
  requestBody: TokenPatch
  tokenId: string
}

export type PatchUserTokenResponse = UserTokenPublic

export type DeleteUserTokenData = {
  tokenId: string
}

export type DeleteUserTokenResponse = Message

export type GetUserGithubAppInstallationsResponse = GitHubInstallations

export type GetUserConnectedAccountsResponse = ConnectedAccounts

export type PostUserZenodoAuthData = {
  requestBody: OAuthCodeExchange
}

export type PostUserZenodoAuthResponse = Message

export type GetUserZenodoTokenResponse = ExternalTokenResponse

export type GetUserGithubTokenResponse = ExternalTokenResponse

export type GetUserOverleafTokenResponse = ExternalTokenResponse

export type PutUserOverleafTokenData = {
  requestBody: TokenPut
}

export type PutUserOverleafTokenResponse = Message

export type PostUserGoogleAuthData = {
  requestBody: OAuthCodeExchange
}

export type PostUserGoogleAuthResponse = Message

export type PostUserGithubAuthData = {
  requestBody: OAuthCodeExchange
}

export type PostUserGithubAuthResponse = Message

export type PostUserZoteroAuthStartResponse = ZoteroAuthStart

export type PostUserZoteroAuthData = {
  requestBody: ZoteroAuthFinish
}

export type PostUserZoteroAuthResponse = Message

export type DeleteUserExternalCredentialData = {
  provider: string
}

export type DeleteUserExternalCredentialResponse = Message

export type GetUserStorageResponse = StorageUsage
