"""The project content a document uses, and whether it is still current.

A document that injects project content -- a number from a results file, a
figure a stage plotted, a block of generated prose -- doesn't hold copies of
those things, it holds *components*: places where the project's own output
appears on the page. This module is what turns a place in a document back
into the file, stage and script behind it, and says whether what the reader
is looking at is still what the project produces.

Being out of date is not one condition but several, and they are
independent:

- The **stage is out of date**, so the artifact itself needs a rerun before
  the document is even worth rebuilding.
- The **document was built against something that has since changed**, so
  the PDF in front of you shows a number or a figure the project no longer
  produces, whatever the pipeline's state.
- The **answer behind a generated block** no longer matches its evidence,
  which is a person's job to fix rather than the pipeline's.

All of them are reported, and any of them can hold at once. Separate from
all of it is whether the component has any provenance at all: a file no
stage produces and nobody has declared reached the page from nowhere, and
no amount of rerunning fixes that.

Everything here reads the document's ``<document>.provenance.json``
sidecar, ``calkit.yaml`` and ``dvc.lock``; a position in the source can be
resolved without a sidecar, so an editor can answer "where did this come
from?" in a project that has never been built.

The sidecar is the contract, not LaTeX. Any format that writes one gets
the same answers from the same code, and so does any reader: the checkout
the CLI has and the Git tree a server reads differ only in a
:class:`ProjectView`, never in what counts as out of date.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

import calkit

ComponentKind = Literal["value", "figure", "text", "block"]
#: Where a component's source file came from, strongest first. A pipeline
#: stage is the only one of these that is checked rather than claimed;
#: "undeclared" is the hole -- no stage makes it, nobody says they made
#: it, and it isn't recorded as coming from anywhere.
Provenance = Literal[
    "pipeline", "imported", "attested", "project", "undeclared"
]
ComponentStatus = Literal["ok", "stale", "missing", "unknown"]
StaleReason = Literal[
    "stage-out-of-date", "changed-since-build", "answer-stale"
]

#: Commands from calkit.sty that name a project path directly, and the kind
#: of component each one makes. The plain LaTeX equivalents are included
#: because a document can use them without the package and still be asking
#: about the same file.
PATH_COMMANDS: dict[str, ComponentKind] = {
    "ckfigure": "figure",
    "includegraphics": "figure",
    "includesvg": "figure",
    "ckinput": "text",
    "input": "text",
    "include": "text",
}
#: Marks a file written by one of the ``*-to-latex`` stages
GENERATED_MARKER = "%% Generated by Calkit"
#: Collections in calkit.yaml whose entries name a path and can say where
#: it came from. Read generically rather than through the models, so a
#: collection gaining attribution needs no change here.
DECLARED_COLLECTIONS = (
    "datasets",
    "figures",
    "publications",
    "presentations",
    "tables",
    "results",
    "misc",
    "software",
    "notebooks",
)


class Component(BaseModel):
    """One piece of project content a document uses."""

    kind: ComponentKind
    #: Project-relative path of the file the content came from
    path: str
    #: Results key for a value, question number for a block
    key: str | None = None
    #: Pages of the built document it appears on, if it has been built
    pages: list[int] = Field(default_factory=list)
    #: The stage that produces ``path``, and what it takes to run it
    stage: str | None = None
    stage_inputs: list[str] = Field(default_factory=list)
    #: The stage's script or notebook, which is what someone wants to open
    script: str | None = None
    #: Where the source file came from, and nothing at all if "undeclared"
    provenance: Provenance = "undeclared"
    #: The text as the document typesets it, for showing someone
    document_value: str | None = None
    #: The raw value behind it when the document was built, and now. Raw,
    #: because the same value can be typeset several ways in one document
    #: ("{ratio:.1f}" and "{ratio}"), and a difference in formatting is not
    #: a difference in the result.
    build_value: Any = None
    current_value: Any = None
    #: Hash of ``path`` when the document was built, and now
    build_hash: str | None = None
    current_hash: str | None = None
    status: ComponentStatus = "unknown"
    stale_reasons: list[StaleReason] = Field(default_factory=list)
    #: Every place in the source this component is written. Empty for one
    #: the built document used and the source no longer names.
    locations: list[Location] = Field(default_factory=list)

    @property
    def location(self) -> str:
        """How to name this component to a person."""
        return self.path + (f":{self.key}" if self.key else "")


class Location(BaseModel):
    """Where a component is written in a document's source."""

    #: Project-relative path of the file it is written in
    source: str
    #: 1-based, as editors count
    line: int
    column: int


class DocumentComponents(BaseModel):
    """Every component of one document."""

    document: str
    #: Whether a build has left a provenance sidecar to read
    built: bool = False
    components: list[Component] = Field(default_factory=list)

    @property
    def needs_attention(self) -> list[Component]:
        """Components known to be out of date or gone.

        A component nothing could be checked about is not one of them: it
        reads as unknown, which is a fact about the check, not the
        component.
        """
        return [c for c in self.components if c.status in ("stale", "missing")]


def _unescape_tex(text: str) -> str:
    """Undo :func:`calkit.latex.escape_tex`.

    Keys and paths are escaped on their way into the generated LaTeX, and
    have to be plain again to look anything up in a results file or on
    disk.
    """
    for plain, escaped in (
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
        ("\\", r"\textbackslash{}"),
    ):
        text = text.replace(escaped, plain)
    return re.sub(r"\\([&%$#_{}])", r"\1", text)


def _groups(text: str, start: int, count: int) -> tuple[list[str], int]:
    """Read ``count`` brace groups beginning at ``start``.

    Brace matching rather than a regex, since a value can itself contain
    braces (``\\textbackslash{}`` for one). Returns the group contents and
    the index just past the last one, or fewer groups than asked for if the
    text runs out.
    """
    out: list[str] = []
    i = start
    while len(out) < count:
        while i < len(text) and text[i] in " \t\n":
            i += 1
        if i >= len(text) or text[i] != "{":
            break
        depth = 0
        j = i
        while j < len(text):
            if text[j] == "{" and (j == i or text[j - 1] != "\\"):
                depth += 1
            elif text[j] == "}" and text[j - 1] != "\\":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        if j >= len(text):
            break
        out.append(text[i + 1 : j])
        i = j + 1
    return out, i


def components_in_tex(tex: str) -> list[dict]:
    """The components a fragment of LaTeX makes.

    Used both on the expansion of a generated command and on a line of a
    document's source, so ``\\result[Improvement]`` and a bare
    ``\\includegraphics{...}`` are read by the same code.
    """
    found: list[dict] = []
    for match in re.finditer(r"\\ckvalue", tex):
        args, _ = _groups(tex, match.end(), 4)
        if len(args) < 4:
            continue
        key, value, path, _stage = args
        found.append(
            {
                "kind": "value",
                "path": _unescape_tex(path),
                "key": _unescape_tex(key),
                "document_value": _unescape_tex(value),
            }
        )
    for match in re.finditer(r"\\ckblock", tex):
        args, _ = _groups(tex, match.end(), 2)
        if len(args) < 2:
            continue
        found.append(
            {
                "kind": "block",
                "path": _unescape_tex(args[1]),
                "key": _unescape_tex(args[0]),
            }
        )
    return found


#: How far to follow one generated command into another. \\ckfindings
#: expands to \\ckanswer, which expands to the values in the answer, and
#: the limit is what stops a cycle rather than a real depth in practice.
_EXPAND_DEPTH = 4
#: A control sequence, with the optional key a generated command takes
_COMMAND_RE = re.compile(r"\\(\w+)\s*(?:\[([^\]]*)\])?")


def _bodies(entries: dict[str, str], key: str | None) -> list[str]:
    """The expansions a generated command produces for a key.

    A command called with no key prints everything it has, so that is what
    a cursor on it is asking about.
    """
    if key is None:
        key = "" if "" in entries else "all"
    if key == "all":
        return list(entries.values())
    return [entries[key]] if key in entries else []


def expand_components(
    tex: str, commands: dict[str, dict[str, str]], depth: int = _EXPAND_DEPTH
) -> list[dict]:
    """Components in a fragment, following generated commands it calls.

    ``\\ckfindings`` holds ``\\ckanswer[1]``, and the values a reader sees
    are inside that, so a fragment's components are only complete once the
    commands it calls have been expanded too.
    """
    found = components_in_tex(tex)
    if depth <= 0:
        return found
    for match in _COMMAND_RE.finditer(tex):
        entries = commands.get(match.group(1))
        if entries is None:
            continue
        for body in _bodies(entries, match.group(2)):
            found += expand_components(body, commands, depth - 1)
    return found


def generated_commands(
    target_path: str, wdir: str | None = None
) -> dict[str, dict[str, str]]:
    """Command name -> key -> the LaTeX it expands to, for one document.

    Read from the ``.tex`` files the ``*-to-latex`` stages generate, which
    is where the tie between ``\\result[Improvement]`` and a results file
    is written down. Only Calkit-generated files are parsed, so a
    document's own macros are left alone.
    """
    from calkit.latex import detect_inputs

    wdir = wdir or os.getcwd()
    out: dict[str, dict[str, str]] = {}
    paths = [target_path] + detect_inputs(target_path, wdir)
    for rel in paths:
        if not rel.endswith(".tex"):
            continue
        try:
            tex = (Path(wdir) / rel).read_text(
                encoding="utf-8", errors="replace"
            )
        except OSError:
            continue
        if not tex.startswith(GENERATED_MARKER):
            continue
        # One generated file can define several commands (the questions
        # file defines five), so each branch is attributed by the command
        # name in its own \def, never by proximity to a \newcommand.
        for branch in re.finditer(
            r"\\ifnum\\pdfstrcmp\{#1\}\{([^}]*)\}=0%\s*\\def\\(\w+)@out",
            tex,
        ):
            body, _ = _groups(tex, branch.end(), 1)
            if body:
                out.setdefault(branch.group(2), {})[branch.group(1)] = body[0]
        # \ckfindings takes no key, so it has no branches to read
        for match in re.finditer(r"\\newcommand\\(ckfindings)", tex):
            body, _ = _groups(tex, match.end(), 1)
            if body:
                out.setdefault(match.group(1), {})[""] = body[0]
    return out


class ProjectView:
    """What classifying a component needs to know about a project.

    A checkout answers these from the filesystem; a server answers them
    from a Git tree at some ref, and a document in some other format
    answers them however it likes. What is written down in ``calkit.yaml``
    is the same either way, so it is answered here once; anything that
    needs the project's files is left to a subclass, and the judgment
    about whether a component is still current stays in one place for all
    of them.
    """

    def __init__(self, ck_info: dict) -> None:
        self.ck_info = ck_info
        self._stages = ck_info.get("pipeline", {}).get("stages", {}) or {}

    # -- Answered from calkit.yaml, wherever the project is read from --

    def stage_for(self, path: str) -> str | None:
        """The stage that produces a path, if the pipeline makes it."""
        from calkit.pipeline import get_stage_for_output

        return get_stage_for_output(path, self.ck_info)

    def stage_inputs(self, stage: str | None) -> list[str]:
        config = self._stages.get(stage) if stage else None
        if not isinstance(config, dict):
            return []
        return [
            inp if isinstance(inp, str) else json.dumps(inp)
            for inp in config.get("inputs") or []
        ]

    def script_for(self, stage: str | None) -> str | None:
        """The file someone would open to change what a stage produces."""
        config = self._stages.get(stage) if stage else None
        if not isinstance(config, dict):
            return None
        for key in ("script_path", "notebook_path", "target_path"):
            value = config.get(key)
            if isinstance(value, str):
                return value
        return None

    def declared_as(self, path: str) -> Provenance:
        """Whether anything is recorded about where a file came from.

        Only the declaration: a path the pipeline produces is answered
        before this is asked.
        """
        for collection in DECLARED_COLLECTIONS:
            for entry in self.ck_info.get(collection) or []:
                if not isinstance(entry, dict):
                    continue
                if Path(str(entry.get("path", ""))).as_posix() != path:
                    continue
                if entry.get("imported_from"):
                    return "imported"
                if entry.get("created_by"):
                    return "attested"
        return "undeclared"

    # -- Answered from the project's files, so where they are matters --

    def exists(self, path: str) -> bool:
        """Whether the project still has this file."""
        raise NotImplementedError

    def current_hash(self, path: str) -> str | None:
        """The hash of a path now, as the pipeline would record it."""
        raise NotImplementedError

    def read_results(self, path: str) -> Any:
        """A results file, loaded. Raises if it can't be read."""
        raise NotImplementedError

    def stale_stages(self) -> set[str] | None:
        """Stages the pipeline would rerun, or None if nothing looked.

        None and the empty set mean different things: nothing known versus
        nothing stale, and a component shouldn't be called current on the
        strength of a check that never ran.
        """
        return None

    def stale_answers(self) -> set[str]:
        """Question numbers whose answers no longer match their evidence."""
        return set()

    def current_value(self, path: str, key: str | None) -> Any:
        """What the project says a value is now, raw, or None if unreadable.

        A key the document made up out of a ``--format-json`` expression
        has nothing behind it in the file, and reads as unknown rather
        than as a mismatch.
        """
        if not key:
            return None
        from calkit.questions import resolve_key

        try:
            return resolve_key(self.read_results(path), key)
        except (OSError, KeyError, ValueError, TypeError):
            return None


class LocalProject(ProjectView):
    """A project as a working directory, which is what the CLI has."""

    def __init__(
        self,
        ck_info: dict,
        wdir: str,
        check_stages: bool = True,
    ) -> None:
        super().__init__(ck_info)
        self.wdir = wdir
        self.check_stages = check_stages
        self._lock: dict[str, str] | None = None
        self._stale_stages: set[str] | None = None
        self._looked_for_stale_stages = False
        self._stale_answers: set[str] | None = None

    def exists(self, path: str) -> bool:
        full = os.path.join(self.wdir, path)
        # A DVC-tracked file that hasn't been pulled is still the
        # project's, and its pointer is always in Git
        return os.path.exists(full) or os.path.isfile(full + ".dvc")

    def current_hash(self, path: str) -> str | None:
        if self._lock is None:
            from calkit.latex import _lock_hashes

            self._lock = _lock_hashes(self.wdir)
        if self._lock.get(path):
            return self._lock[path]
        # A Git-stored output has no dvc.lock entry, so its content is
        # hashed the same way DVC would, which keeps the comparison
        # meaningful for the generated .tex files and anything else in Git
        full = os.path.join(self.wdir, path)
        if not os.path.isfile(full):
            return None
        digest = hashlib.md5()
        with open(full, "rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                digest.update(chunk)
        return digest.hexdigest()

    def read_results(self, path: str) -> Any:
        from calkit.questions import read_evidence_file

        return read_evidence_file(os.path.join(self.wdir, path))

    def stale_stages(self) -> set[str] | None:
        if not self.check_stages or self._looked_for_stale_stages:
            return self._stale_stages
        self._looked_for_stale_stages = True
        import calkit.pipeline

        try:
            status = calkit.pipeline.get_status(
                ck_info=self.ck_info,
                wdir=self.wdir,
                check_environments=False,
                clean_notebooks=False,
            )
        except Exception:
            return None
        # An iterated stage is keyed 'name@param' in the pipeline status,
        # but an output belongs to the stage as calkit.yaml writes it
        self._stale_stages = {
            name.split("@")[0] for name in status.stale_stage_names
        }
        return self._stale_stages

    def stale_answers(self) -> set[str]:
        if self._stale_answers is not None:
            return self._stale_answers
        self._stale_answers = set()
        if self.ck_info.get("questions"):
            from calkit.questions import check_questions

            try:
                status = check_questions(ck_info=self.ck_info, wdir=self.wdir)
                self._stale_answers = {
                    str(q.index)
                    for q in status.questions
                    if q.status in ("stale", "error")
                }
            except Exception:
                pass
        return self._stale_answers


def enrich(raw: list[dict], view: ProjectView) -> list[Component]:
    """Turn bare ``{kind, path, key}`` records into full components.

    This is the whole point of the module: given only where something came
    from, say which stage makes it, what to open to change it, and whether
    what the document shows is still what the project produces. Everything
    it needs comes through the view, so the same judgment is reached from
    a checkout, from a Git tree on a server, and from any document format
    that can say what it injected.
    """
    stale_stages = view.stale_stages()
    stale_answers = (
        view.stale_answers()
        if any(r.get("kind") == "block" for r in raw)
        else set()
    )
    out: list[Component] = []
    for rec in raw:
        path = rec["path"]
        kind = rec.get("kind", "value")
        stage_name = view.stage_for(path)
        component = Component(
            kind=kind,
            path=path,
            key=rec.get("key") or None,
            pages=rec.get("pages") or [],
            stage=stage_name,
            stage_inputs=view.stage_inputs(stage_name),
            script=view.script_for(stage_name),
            # A block is the project's own words in calkit.yaml, so there
            # is no outside source to account for
            provenance=(
                "project"
                if kind == "block"
                else "pipeline"
                if stage_name
                else view.declared_as(path)
            ),
            document_value=rec.get("document_value"),
            build_value=rec.get("value"),
            build_hash=rec.get("hash"),
            locations=rec.get("locations") or [],
        )
        component.current_hash = view.current_hash(path)
        if kind == "value":
            component.current_value = view.current_value(path, component.key)
        reasons: list[StaleReason] = []
        # Calling something current means something was actually checked,
        # so each check that could run says so; a component nothing could
        # be said about reads as unknown rather than as fine
        checked = stale_stages is not None
        if stale_stages is not None and stage_name in stale_stages:
            reasons.append("stage-out-of-date")
        if kind == "block":
            checked = True
            if component.key in stale_answers:
                reasons.append("answer-stale")
        elif kind == "value":
            # A value is compared value to value: a results file changing
            # in a key the document never cites says nothing about the
            # page. Only a build records the value it used, so an unbuilt
            # document leans on its stage's status instead.
            if component.build_value is not None:
                checked = True
                if component.build_value != component.current_value:
                    reasons.append("changed-since-build")
        elif component.build_hash and component.current_hash:
            checked = True
            if component.build_hash != component.current_hash:
                reasons.append("changed-since-build")
        component.stale_reasons = reasons
        if not view.exists(path):
            component.status = "missing"
        elif reasons:
            component.status = "stale"
        else:
            component.status = "ok" if checked else "unknown"
        out.append(component)
    return out


def read_sidecar(document: str, wdir: str | None = None) -> dict | None:
    """The provenance record a build left beside a document, if any.

    Accepts the source, the built PDF, or the sidecar itself, since a tool
    asking about a document has whichever of those the user was looking
    at.
    """
    import calkit.latex

    wdir = wdir or os.getcwd()
    if document.endswith(".provenance.json"):
        path = document
    else:
        path = calkit.latex.provenance_sidecar_path(document)
    full = os.path.join(wdir, path)
    if not os.path.isfile(full):
        return None
    try:
        with open(full, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


def source_path(document: str) -> str:
    """The LaTeX source behind whatever the caller named the document as."""
    for suffix in (".provenance.json", ".pdf"):
        if document.endswith(suffix):
            return document[: -len(suffix)] + ".tex"
    return document


def latex_documents(ck_info: dict) -> list[str]:
    """Every LaTeX document the pipeline builds."""
    stages = ck_info.get("pipeline", {}).get("stages", {}) or {}
    return [
        stage["target_path"]
        for stage in stages.values()
        if isinstance(stage, dict)
        and stage.get("kind") == "latex"
        and isinstance(stage.get("target_path"), str)
    ]


def document_for_source(
    source: str, ck_info: dict, wdir: str | None = None
) -> str | None:
    """The document a source file belongs to.

    A paper split across files means the cursor is often somewhere the
    sidecar and the generated commands can only be found through the root
    document, and an editor shouldn't have to work that out. A file that
    is itself a document is its own answer; otherwise it is whichever
    document reads it.
    """
    from calkit.latex import detect_inputs

    wdir = wdir or os.getcwd()
    source = Path(source).as_posix()
    documents = latex_documents(ck_info)
    if source in documents:
        return source
    for document in documents:
        if source in detect_inputs(document, wdir):
            return document
    return documents[0] if len(documents) == 1 else None


def describe_document(
    document: str,
    ck_info: dict | None = None,
    wdir: str | None = None,
    check_stages: bool = True,
) -> DocumentComponents:
    """Every component of a document, with where it came from and its state.

    Prefers the sidecar, which knows what the built document actually
    shows and on which pages. Without one -- nothing built yet -- the
    source is read instead, so the answer is about what the next build
    would contain.
    """
    wdir = wdir or os.getcwd()
    if ck_info is None:
        ck_info = calkit.load_calkit_info(wdir=wdir)
    sidecar = read_sidecar(document, wdir)
    view = LocalProject(ck_info, wdir, check_stages)
    if sidecar is not None:
        target = sidecar.get("document", source_path(document))
        # The build says what the document shows; only the source says
        # where it is written, which is what an editor needs to put a
        # marker on the right line. A component with no location is one
        # the source stopped naming after the build.
        locations = {
            (rec["kind"], rec["path"], rec.get("key")): rec["locations"]
            for rec in _source_components(target, wdir)
        }
        components = [
            {
                **rec,
                "locations": locations.get(
                    (rec.get("kind"), rec.get("path"), rec.get("key")), []
                ),
            }
            for rec in sidecar.get("components", [])
        ]
        return DocumentComponents(
            document=target,
            built=True,
            components=enrich(components, view),
        )
    target = source_path(document)
    return DocumentComponents(
        document=target,
        built=False,
        components=enrich(_source_components(target, wdir), view),
    )


def _is_generated(path: str, wdir: str) -> bool:
    """Whether a file is one the ``*-to-latex`` stages wrote."""
    try:
        with open(os.path.join(wdir, path), encoding="utf-8") as f:
            return f.read(len(GENERATED_MARKER)) == GENERATED_MARKER
    except OSError:
        return False


def _line_col(line_starts: list[int], offset: int) -> tuple[int, int]:
    """A character offset as a 1-based line and column, as editors count."""
    import bisect

    index = bisect.bisect_right(line_starts, offset) - 1
    return index + 1, offset - line_starts[index] + 1


def _source_components(target: str, wdir: str) -> list[dict]:
    """What a document's source uses, and where each of it is written.

    Only what the source actually calls: a generated file typically
    defines every value in a results file, and a document that cites three
    of them uses three. This is the same set the build would log, plus the
    places in the source and minus the pages.
    """
    from calkit.latex import _strip_comments, detect_inputs

    commands = generated_commands(target, wdir)
    out: list[dict] = []
    by_key: dict[tuple, dict] = {}

    def add(rec: dict, source: str, offset: int, starts: list[int]) -> None:
        key = (rec["kind"], rec["path"], rec.get("key"))
        existing = by_key.get(key)
        if existing is None:
            existing = dict(rec)
            existing["locations"] = []
            by_key[key] = existing
            out.append(existing)
        line, column = _line_col(starts, offset)
        location = Location(source=source, line=line, column=column)
        if location not in existing["locations"]:
            existing["locations"].append(location)

    for rel in [target] + detect_inputs(target, wdir):
        # A generated file's own contents are reached by expanding the
        # commands the document calls, not by reading it as a source
        if not rel.endswith(".tex") or _is_generated(rel, wdir):
            continue
        try:
            # Comments are blanked in place rather than removed, so an
            # offset still names the same line and column it did
            tex = _strip_comments(
                (Path(wdir) / rel).read_text(
                    encoding="utf-8", errors="replace"
                )
            )
        except OSError:
            continue
        starts = [0] + [i + 1 for i, c in enumerate(tex) if c == "\n"]
        for match in _COMMAND_RE.finditer(tex):
            entries = commands.get(match.group(1))
            if entries is None:
                continue
            for body in _bodies(entries, match.group(2)):
                for rec in expand_components(body, commands):
                    add(rec, rel, match.start(), starts)
        for span, rec in _path_commands(tex, target, rel, wdir):
            # Pulling in a generated file is the mechanism, not a
            # component: what it carries is already listed as the values
            # and blocks the document shows
            if rec["kind"] == "text" and _is_generated(rec["path"], wdir):
                continue
            add(rec, rel, span[0], starts)
    return out


def _resolve_tex_path(raw: str, target: str, source: str, wdir: str) -> str:
    """A path as a document writes it, as a project path.

    TeX resolves against the root document's directory; a file written as
    if paths were relative to itself is common enough to try too, which is
    the same pair :func:`calkit.latex.detect_inputs` tries.
    """
    from calkit.latex import _GRAPHICS_EXTS, _project_has

    base = Path(wdir)
    parents = dict.fromkeys([Path(target).parent, Path(source).parent])
    names = [raw] + [raw + ext for ext in _GRAPHICS_EXTS] + [raw + ".tex"]
    for name in names:
        for parent in parents:
            rel = Path(os.path.normpath(parent / name)).as_posix()
            if not rel.startswith("..") and _project_has(base, rel):
                return rel
    return Path(os.path.normpath(Path(target).parent / raw)).as_posix()


def _path_commands(
    text: str, target: str, source: str, wdir: str
) -> list[tuple[tuple[int, int], dict]]:
    """Path-naming commands in a fragment of source, with their spans."""
    found = []
    pattern = re.compile(
        r"\\(" + "|".join(PATH_COMMANDS) + r")\s*(?:\[[^\]]*\])*\s*\{"
    )
    for match in pattern.finditer(text):
        args, end = _groups(text, match.end() - 1, 1)
        if not args:
            continue
        for raw in [n.strip() for n in args[0].split(",")]:
            if not raw or raw.startswith(("http://", "https://")):
                continue
            found.append(
                (
                    (match.start(), end),
                    {
                        "kind": PATH_COMMANDS[match.group(1)],
                        "path": _resolve_tex_path(raw, target, source, wdir),
                    },
                )
            )
    return found


def resolve_position(
    source: str,
    line: int,
    col: int | None = None,
    document: str | None = None,
    ck_info: dict | None = None,
    wdir: str | None = None,
    check_stages: bool = True,
) -> list[Component]:
    """The components at a place in a document's source.

    This is what an editor asks when the cursor is on ``\\result[Speedup]``
    or a figure: one line, optionally one column, and back comes the file,
    the stage, the script to open and whether any of it needs a rerun.
    Pages and what the built document shows come from the sidecar when
    there is one; without it the answer still holds, minus those.

    ``line`` is 1-based, as editors count, and ``col`` is 1-based too. With
    no column, every component on the line is returned.
    """
    wdir = wdir or os.getcwd()
    if ck_info is None:
        ck_info = calkit.load_calkit_info(wdir=wdir)
    target = source_path(document or source)
    try:
        lines = (
            (Path(wdir) / source)
            .read_text(encoding="utf-8", errors="replace")
            .splitlines()
        )
    except OSError:
        return []
    if line < 1 or line > len(lines):
        return []
    text = lines[line - 1]
    commands = generated_commands(target, wdir)
    hits: list[tuple[tuple[int, int], dict]] = []
    # A generated command: \result[Improvement], \ckanswer[2], \ckfindings
    for match in _COMMAND_RE.finditer(text):
        entries = commands.get(match.group(1))
        if entries is None:
            continue
        for body in _bodies(entries, match.group(2)):
            for rec in expand_components(body, commands):
                hits.append(((match.start(), match.end()), rec))
    hits += _path_commands(text, target, source, wdir)
    if col is not None:
        hits = [h for h in hits if h[0][0] <= col - 1 < h[0][1]]
    if not hits:
        return []
    # Fold in what the build recorded, so a hover shows the pages a value
    # lands on and compares against what the reader is actually looking at
    sidecar = read_sidecar(document or target, wdir) or {}
    built = {
        (c.get("kind"), c.get("path"), c.get("key") or None): c
        for c in sidecar.get("components", [])
    }
    raw = []
    for _, rec in hits:
        key = (rec["kind"], rec["path"], rec.get("key") or None)
        # The build knows the pages and the value it used; the source knows
        # how this particular occurrence is typeset, which the build's log
        # cannot tell apart from any other occurrence of the same key
        merged = dict(built.get(key, {}))
        merged.update({k: v for k, v in rec.items() if v is not None})
        raw.append(merged)
    return enrich(raw, LocalProject(ck_info, wdir, check_stages))
