"""Add fields to usertoken

Revision ID: 07c8236476c4
Revises: 9c4f70636d73
Create Date: 2025-07-23 19:37:37.018702

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '07c8236476c4'
down_revision = '9c4f70636d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertoken', sa.Column('selector', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('usertoken', sa.Column('hashed_verifier', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.drop_index(op.f('ix_usertoken_hashed_token'), table_name='usertoken')
    op.create_index(op.f('ix_usertoken_selector'), 'usertoken', ['selector'], unique=True)
    op.drop_column('usertoken', 'hashed_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertoken', sa.Column('hashed_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_usertoken_selector'), table_name='usertoken')
    op.create_index(op.f('ix_usertoken_hashed_token'), 'usertoken', ['hashed_token'], unique=True)
    op.drop_column('usertoken', 'hashed_verifier')
    op.drop_column('usertoken', 'selector')
    # ### end Alembic commands ###
