"""Add title to project

Revision ID: 208e7457f3ba
Revises: 7076d9b5c887
Create Date: 2024-09-09 19:52:27.640596

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "208e7457f3ba"
down_revision = "7076d9b5c887"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "title",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "title")
    # ### end Alembic commands ###
