"""Add is_public to Project

Revision ID: 2e7c25a00842
Revises: 697c3c1a8a27
Create Date: 2024-08-06 15:58:20.514254

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2e7c25a00842'
down_revision = '697c3c1a8a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_public')
    # ### end Alembic commands ###
