"""Add status columns to project table

Revision ID: 4e1c917fcca4
Revises: 7cacee34034c
Create Date: 2025-02-17 15:07:42.516170

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e1c917fcca4'
down_revision = '7cacee34034c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('project', sa.Column('status_updated', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'status_message')
    op.drop_column('project', 'status_updated')
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
