"""Add subscriber user ID to org subscription

Revision ID: 5d6f8217c890
Revises: 38e178698db2
Create Date: 2024-09-14 02:23:49.898789

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5d6f8217c890'
down_revision = '38e178698db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgsubscription', sa.Column('subscriber_user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'orgsubscription', 'user', ['subscriber_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orgsubscription', type_='foreignkey')
    op.drop_column('orgsubscription', 'subscriber_user_id')
    # ### end Alembic commands ###
