"""Add git_repo_url to Project

Revision ID: 697c3c1a8a27
Revises: 1546aa334cd5
Create Date: 2024-08-05 14:30:40.629269

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '697c3c1a8a27'
down_revision = '1546aa334cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('git_repo_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'git_repo_url')
    # ### end Alembic commands ###
