"""Add number field to Question

Revision ID: 6f3a3afbea8b
Revises: f0e23e048b1b
Create Date: 2024-09-07 12:46:35.224901

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6f3a3afbea8b'
down_revision = 'f0e23e048b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
