"""Add created_ts to user GitHub token table

Revision ID: 799476973bce
Revises: 71e1d1e69bbd
Create Date: 2024-08-10 19:17:14.079732

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '799476973bce'
down_revision = '71e1d1e69bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergithubtoken', sa.Column('updated_ts', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usergithubtoken', 'updated_ts')
    # ### end Alembic commands ###
