"""Add parent/child relationship to projects

Revision ID: 7cacee34034c
Revises: d21ed1c9537e
Create Date: 2024-12-18 18:24:31.618191

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7cacee34034c'
down_revision = 'd21ed1c9537e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('parent_project_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'project', 'project', ['parent_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'parent_project_id')
    # ### end Alembic commands ###
