"""Add fields to UserToken

Revision ID: 9c4f70636d73
Revises: f5ad6445ad03
Create Date: 2025-07-23 18:29:25.715969

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9c4f70636d73'
down_revision = 'f5ad6445ad03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usertoken', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.add_column('usertoken', sa.Column('last_used', sa.DateTime(), nullable=True))
    op.add_column('usertoken', sa.Column('hashed_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_usertoken_hashed_token'), 'usertoken', ['hashed_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usertoken_hashed_token'), table_name='usertoken')
    op.drop_column('usertoken', 'hashed_token')
    op.drop_column('usertoken', 'last_used')
    op.drop_column('usertoken', 'description')
    # ### end Alembic commands ###
