"""Save timestamps for GitHub token expiration

Revision ID: ac622559475f
Revises: 799476973bce
Create Date: 2024-08-11 14:41:08.081662

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac622559475f'
down_revision = '799476973bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergithubtoken', sa.Column('updated', sa.DateTime(), nullable=False))
    op.add_column('usergithubtoken', sa.Column('expires', sa.DateTime(), nullable=True))
    op.add_column('usergithubtoken', sa.Column('refresh_token_expires', sa.DateTime(), nullable=True))
    op.drop_column('usergithubtoken', 'refresh_token_expires_in')
    op.drop_column('usergithubtoken', 'expires_in')
    op.drop_column('usergithubtoken', 'updated_ts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergithubtoken', sa.Column('updated_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('usergithubtoken', sa.Column('expires_in', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('usergithubtoken', sa.Column('refresh_token_expires_in', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('usergithubtoken', 'refresh_token_expires')
    op.drop_column('usergithubtoken', 'expires')
    op.drop_column('usergithubtoken', 'updated')
    # ### end Alembic commands ###
