"""Add FigureComment

Revision ID: c749b39072d3
Revises: ac622559475f
Create Date: 2024-08-22 21:51:38.225429

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = 'c749b39072d3'
down_revision = 'ac622559475f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('figurecomment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('figure_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False, server_default=func.now()),
    sa.Column('updated', sa.DateTime(), nullable=False, server_onupdate=func.now()),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('figurecomment')
    # ### end Alembic commands ###
