"""Add operator table

Revision ID: cc224455e0bb
Revises: c4e1d7a92b35
Create Date: 2026-09-26 16:12:53.455652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cc224455e0bb'
down_revision = 'c4e1d7a92b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('machine_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('calkit_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('hosts', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('workspaces', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('connected', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('connect_requested_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('selector', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('hashed_verifier', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_operator_user_name')
    )
    op.create_index(op.f('ix_operator_selector'), 'operator', ['selector'], unique=True)
    op.create_index(op.f('ix_operator_user_id'), 'operator', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_user_id'), table_name='operator')
    op.drop_index(op.f('ix_operator_selector'), table_name='operator')
    op.drop_table('operator')
    # ### end Alembic commands ###
