"""Add zenodo_user_id column to user

Revision ID: d21ed1c9537e
Revises: a4af19842927
Create Date: 2024-09-24 15:27:16.473344

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd21ed1c9537e'
down_revision = 'a4af19842927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zenodo_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zenodo_user_id')
    # ### end Alembic commands ###
